server:
  port: 9000

spring:
  mvc:

    pathmatch:

      matching-strategy: ant_path_matcher

  application:
    name: demo

  datasource:
    url: jdbc:mysql://rcdb.camd5cd2mgun.ap-northeast-2.rds.amazonaws.com/realMe?autoReconnect=true
    username: dee0329
    password: gozjxhs12!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

  jpa:
    hibernate:
      ddl-auto: create-drop

