# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "Develop" branch
  push:
    branches: [ "develop"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # https://github.com/actions/setup-java

      ## create application-secret.yml
      - name: make application-secret.yml
        #if: contains(github.ref, 'develop')
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APP_YML }}" > ./application.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash

#      - name: Test with Gradle
#        run: ./gradlew test

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            mkdir -p /home/ubuntu/realme-backend
            cd /home/ubuntu/realme-backend
             echo -e "\
             +------------------------------------+
             |              1. build              |
             +------------------------------------+"
            
            echo ">>>>>> making secret yml..."
            mkdir -p ./src/main/resources
            echo "${{ secrets.APP_YML }}" > ./src/main/resources/application.yml
                        
            echo -e "\
            >>>>>> git pull... "
            git fetch --all || exit 1
            git reset --hard origin/develop || exit 1
            git pull origin develop || exit 1

            echo ">>>>>> build..."
            ./gradlew clean build -x test || exit 1
            ./scripts/stop.sh || exit 1
            ./scripts/start.sh || exit 1